version: '{build}'
os: Windows Server 2012

environment:
  global:
      PYTHON: "C:\\conda"
      PYTHON_ARCH: "64"
  matrix:
      - PYTHON_VERSION: "3.5"
        CONDA_DEPENDENCIES: "setuptools pytest pyqt=4.* qt=4.*"
        PIP_DEPENDENCIES: "pytest-qt"

platform:
    -x64

install:
  # Install conda using ci-helpers. More information about ci-helpers can
  # be found here: https://github.com/astropy/ci-helpers
  - "git clone git://github.com/astropy/ci-helpers.git"
  - "rm ci-helpers/test_env.py"
  - "powershell ci-helpers/appveyor/install-miniconda.ps1"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  - "activate test"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  # Run the project tests (don't do examples because they are too slow)
  - "py.test -s guitest.py"
